### ISSUE TITLE
Deploy to Flathub

### ISSUE THREAD

**Issue by Cediddi** [mkfrey/com.microsoft.AzureStorageExplorer#6]
I think this would be really nice. Please let me know if there are any issues that I can help with. I can also take the maintenance from you, if you are not willing to invest time.

**Comment by mkfrey** [comment]
Deployment has been requested: https://github.com/flathub/flathub/pull/4741

**Comment by mkfrey** [comment]
Merged: https://github.com/flathub/com.microsoft.AzureStorageExplorer
